tresais majasdarbs
Signe-Sn/Codelex-Majasdarbi- pull request #4
Opened 2022-09-20 18:23 UTC by Signe-Sn

2022-10-21 17:56 UTC, NilsKula requested changes

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/arrays/practice/Exercise6.java
> +        myArr[9] = -7;
9 varētu aizstāt labāk ar dinamisku vērtību

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/arrays/practice/Hangman.java
> +                if (wrongCount >= 15) {
15 definēt kā konstanti

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/arrays/practice/Hangman.java
> +        return (randomWord.length() == correctGuessCount);
nav nepeiciešamas iekavas

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/arrays/practice/TicTacToe.java
> +    public static char findWinner(char[][] board) {
private

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/classesandobjects/practice/Movie.java
> +    String title;
private

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/classesandobjects/practice/car/Car.java
> +        if (calculateConsumption() > 15.0) {
kostante
kā arī var saīsināt uz vienu rindiņu
`return calculateConsumption() > 15.0`

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/classesandobjects/practice/dog/Dog.java
> +        if (mother.equals(otherDog.mother)){
šeit arī tad var pārveidot uz vienu rindiņu

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/classesandobjects/practice/fuelgauge/FuelGauge.java
> +        if (liters < 70) {
konstante

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/classesandobjects/practice/fuelgauge/Odometer.java
> +    final int kilometersPerLiter = 10;
static final un konstantes klases pašā augšā

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/classesandobjects/practice/fuelgauge/Odometer.java
> +            FuelGauge.burningFuel();
FuleGauge nav statisks, jo katram tas ir savējais, tādēļ tam vajadzetu savu objektu
un tad tu padotu viņū kā parametru metodei
`public void increasingMileage(FuelGauge fuelGauge)`

2022-10-21 17:56 UTC, NilsKula commented on Codelex majasdarbi/src/classesandobjects/practice/savingsaccount/SavingsAccount.java
> +    public double annualInterestRate;
private

2022-10-26 09:02 UTC, Signe-Sn commented on Codelex majasdarbi/src/arrays/practice/Exercise6.java
> +        myArr[9] = -7;
Es īsti nesaprotu kas šeit ir domāts ar dinamisku vērtību?

2022-10-27 14:22 UTC, NilsKula commented on Codelex majasdarbi/src/arrays/practice/Exercise6.java
> +        myArr[9] = -7;
izmantojot array garumu `myArr[myArr.length -1] tā tev nebūs jāmaina kods, ja mainītos izmērs

2022-10-27 14:22 UTC, NilsKula approved these changes

2022-10-27 14:39 UTC, merged